#' @include fitbitr.R
#Constants
url_activity <- paste0(url_api, "activities/")

#' Get Daily Activity Summary
#'
#' Retrieves a summary and list of a user's activities and activity log entries for a given day in the format requested using units in the unit system which corresponds to the Accept-Language header provided.
#'
#' Daily summary data and daily goals for elevation (elevation, floors) only included for users with a device with an altimeter.
#' The steps field in activity log entires included only for activities that have steps (e.g. "Walking", "Running"); distance only included when it is relevant.
#' A false value for field means that activity log entry was created without explicit start time via some of our data import workflows. The field for such entry is commonly set to 00:00.
#' Calorie burn goal (caloriesOut) represents either dynamic daily target from the premium trainer plan or manual calorie burn goal. Goals are included to the response only for today and 21 days in the past.
#' @param token An OAuth 2.0 token generated by oauth_token()
#' @param date The date in the format yyyy-MM-dd
#' @export
get_daily_activity_summary <- function(token, date)
{
  url <- paste0(url_activity, sprintf("date/%s.json", format_date(date)))
  response <- get(url, token)
  convert_content_to_r_object(response)
}

#' Activity Time Series
#'
#' The Get Activity Time Series endpoint returns time series data in the specified range for a given resource in the format requested using units in the unit system that corresponds to the Accept-Language header provided.
#'
#' Even if you provide earlier dates in the request, the response will retrieve only data since the user's join date or the first log entry date for the requested collection.
#' The activities/tracker/... resource represents the daily activity values logged by the tracker device only, excluding manual activity log entries.
#' The activities/tracker/calories resource does not include the Estimated Energy Requirement for calorie estimation (EER) calculations for any dates even if they are turned on for the user's profile and use BMR level instead.
#' The activities collection is maintained as a backwards compatible resource urls (e.g. activities/log/calories).
#' Elevation time series (/elevation, /floors) are only available for users with compatible trackers.
#'
#' @param token An OAuth 2.0 token generated by oauth_token()
#' @param resource_path	The resource path; see options in the "Resource Path Options" section below.
#' @param base_date	The range start date, in the format yyyy-MM-dd or today.
#' @param end_date	The end date of the range.
#' @param date	The end date of the period specified in the format yyyy-MM-dd or today.
#' @param period	The range for which data will be returned. Options are 1d, 7d, 30d, 1w, 1m, 3m, 6m, 1y, or max.
#' @export
get_activity_time_series <- function(token, resource_path, date="", period="", base_date="", end_date="")
{
  url <- if(date != "" && period != ""){
    paste0(url_activity, sprintf("%s/date/%s/%s.json", resource_path, format_date(date), period))
  } else if(base_date != "" & end_date != ""){
    paste0(url_activity, sprintf("%s/date/%s/%s.json", resource_path, format_date(base_date), format_date(end_date)))
  }
  response <- get(url, token)
  data <- convert_content_to_r_object(response)
  data[[1]]
}

#' Get Activity Intraday Time Series
#' Access to the Intraday Time Series for personal use (accessing your own data) is available through the "Personal" App Type.
#' Access to the Intraday Time Series for all other uses is currently granted on a case-by-case basis. Applications must demonstrate necessity to create a great user experience. Fitbit is very supportive of non-profit research and personal projects. Commercial applications require thorough review and are subject to additional requirements. Only select applications are granted access and Fitbit reserves the right to limit this access. To request access, email api@fitbit.com.
#'
#' This endpoint returns the Intraday Time Series for a given resource in the format requested. The endpoint mimics the Get Activity Time Series endpoint. If your application has the appropriate access, your calls to a time series endpoint for a specific day (by using start and end dates on the same day or a period of 1d), the response will include extended intraday values with a 1-minute detail level for that day. Unlike other time series calls that allow fetching data of other users, intraday data is available only for and to the authorized user.
#' If your application's http client is sensitive to the content-length of the response, you will likely prefer JSON as a response format to minimize the amount of data in the response.
#' If a user hasn't synced a tracker for more than seven (7) days, the tracker stores only summary values for the days older than one week. In this case, the intraday data for steps is zero and the intraday calories are calculated from BMR or EER. Intraday steps could be estimated from the total daily summary data by the equation above.
#' For the current day we will include only values until current timestamp (in the user's timezone.)
#' If a specific time interval was passed to the call via start-time/end-time parameters, data-value will include a summary only for the requested time period (versus whole day.)
#' For the activities/log/calories resource, each data point also includes the level field that reflects calculated activity level for that time period ( 0 - sedentary; 1 - lightly active; 2 - fairly active; 3 - very active.)
#' If BMR or EER have been used to estimate calories for the whole specific day (no tracker data), intraday data for calories would be flat and estimated according to the simple equation calories_1m = BMR(EER)/24/60.
#' Using BMR/EER Algorithms
#' If a user had no Fitbit tracker data for the specific day then the greater of Logged Activities + BMR (for minutes when there is no activity) and the calories calculated from the EER for that day (if EER enabled for this user's profile) are taken. In case, there was some data from the tracker for the specific day, that data where available is used and for time where data is unavailable, the BMR is used. If the total is less than 20% greater than BMR then the EER (cals < EER * 0.8) is used. EER never used to calculate calories for today.
#'
#' Using BMR Formula
#' Fitbit uses the standard MD Mifflin-St Jeor equation:
#'
#' 9.99 * weightKg + 6.25*heightCm - 4.92*ageYears + s, where s is +5 for males and -161 for female
#'
#' EER Formula (TEE total energy expenditure)
#'
#' The EER Formula is based on http://www.cdc.gov/pcd/issues/2006/oct/pdf/06_0034.pdf, which in turn is based on "Food and Nutrition Board. Dietary reference intakes for energy, carbohydrate, fiber, fat, fatty acids, cholesterol, protein, and amino acids (macronutrients). Washington (DC): National Academy Press; 2005." http://www.nap.edu/openbook.php?isbn=0309085373&page=204#' MALE-based EER Formula:
#'
#' TEE = 864 - 9.72 x age (years) + 1.0 x (14.2 x weight(kg) + 503 x height (meters))
#'
#' FEMALE-based EER Formula:
#'
#' TEE = 387 - 7.31 x age (years) + 1.0 x (10.9 x weight(kg) + 660.7 x height (meters))
#' @param token An OAuth 2.0 token generated by oauth_token()
#' @param resource_path	The resource path of the desired data.
#' @param date	The date, in the format yyyy-MM-dd or today.
#' @param detail_level	Number of data points to include. Either 1min or 15min. Optional.
#' @param start_time	The start of the period, in the format HH:mm. Optional.
#' @param end_time	The end of the period, in the format HH:mm. Optional.
#' @export
get_activity_intraday_time_series <- function(token, resource_path, date, detail_level, start_time, end_time)
{
  date <- format_date(date)
  url <- paste0(url_activity, sprintf("%s/date/%s/%s/%s.json", resource_path, date, date, detail_level))
  response <- get(url, token)
  convert_content_to_r_object(response)
}

#' Log Activity
#'
#' The Log Activity endpoint creates log entry for an activity or user's private custom activity using units in the unit system which corresponds to the Accept-Language header provided (or using optional custom distanceUnit) and get a response in the format requested.
#'
#' Activity Types
#' Any activity log entry is based on the one of activities from the catalog of activities. Though activities in catalog have a tree structure (i.e. divided into categories like "Sports and Workouts", "Running" and subcategories like "Bicycling", "Walking"), each activity leaf in the catalog can also have more granular structure. Each leaf can have a directory activity type (and have child intensity levels) or simple activity (have no levels). So, when creating a new activity log entry, use the following types of objects to passed as the activityId value:
#' Directory activity id: activity contains child activities which represents intensity levels (e.g. "Running")
#' Intensity level id: activity within directory activity (e.g. "Running/6.7mph (9 min/mile)")
#' Simple activity id: single activity without intensity levels (e.g. "Shoveling snow")
#' Note: A list of activities can be retrieved via the Browse Activities endpoint.
#' Custom Activities
#' In the process of creating new activity log entry it is possible to seamlessly create new custom activity for the user. It could be achieved using the second scenario for the set of POST parameters (providing activityName instead of activityId). In this case, either existing custom activity with the same name will be used for creating new log entry or a new record created and then logged. As for custom activities on the website, manualCalories must always provided with the activityName parameter among other required fields.
#'
#' Note: The steps field is only included for activities that have steps ("Walking" or "Running") and distance is only included when it is relevant.
#' @param token An OAuth 2.0 token generated by oauth_token()
#' @param activity_id	optional/required	This is the Activity ID of the activity, directory activity, or intensity level activity. If you pass directory activity id, Fitbit calculates and substitutes it with the corresponding intensity level activity id based on the specified distance and/or duration.
#' @param activity_name	optional/required	Custom activity name. Either activityId or activityName must be provided.
#' @param manualCalories	optional/required	Calories burned, specified manually. Required with activityName parameter, otherwise optional.
#' @param startTime	required	Activity start time. Hours and minutes in the format HH:mm:ss.
#' @param durationMillis	required	Duration in milliseconds.
#' @param date	required	Log entry date; in the format yyyy-MM-dd.
#' @param distance	optional/required	Distance; required for logging directory activity. In the format X.XX and in the selected distanceUnit or in the unit system that corresponds to the Accept-Language header provided.
#' @param distanceUnit	optional	Distance measurement unit. Steps units are available only for "Walking" (activityId=90013) and "Running" (activityId=90009) directory activities and their intensity levels.
#' @export
log_activity <- function()
{

}

#' Delete Activity Log
#'
#' The Delete Activity Log endpoint deletes a user's activity log entry with the given ID. A successful request will return a 204 status code with an empty response body.
#' @param token An OAuth 2.0 token generated by oauth_token()
#' @param activity_log_id	The id of the activity log entry.
#' @export
delete_activity_log <- function(token, activity_log_id)
{
  url <- paste0(url_activity, activity_log_id, ".json")
  convert_content_to_r_object(delete(url, token))
}


#' Get Activity Logs List
#'
#' Retrieves a list of a user's activity log entries before or after a given day with offset and limit using units in the unit system which corresponds to the Accept-Language header provided.
#' Note: This is a beta feature that will soon have a backwards incompatible change. Please see this announcement.
#' @param token An OAuth 2.0 token generated by oauth_token()
#' @param beforeDate	The date in the format yyyy-MM-ddTHH:mm:ss. Only yyyy-MM-dd is required. Either beforeDate or afterDate should be specified.
#' @param afterDate	The date in the format yyyy-MM-ddTHH:mm:ss.
#' @param sort	The sort order of entries by date asc (ascending) or desc (descending).
#' @param offset	The offset number of entries.
#' @param limit	The max of the number of entries returned (maximum: 100)
#' @export
get_activity_logs_list <- function(token, before_date, after_date, sort, offset, limit)
{
  stop("Sorry, under construction")
  #url <- paste0(url_activity, "list.json")
  #convert_content_to_r_object(get(url, token))
}

#' Get Activity TCX
#' Note: Since this is a beta feature, Fitbit may need to make backwards incompatible changes with less than 30 days notice.
#' The Get Activity TCX endpoint retrieves the details of a user's location and heart rate data during a logged exercise activity.
#' The Training Center XML (TCX) is a data exchange format that contains GPS, heart rate, and lap data, when it is available for the activity. The TCX MIME type is application/vnd.garmin.tcx+xml.
#' TCX requires GPS data and heart data points, which are tied to GPS data points. If you only want heart rate, see the heart rate intraday time series.
#'
#' Finding an "activity's log id"
#' Go to the Activity Logs page in the Fitbit Web app. Click View Details button on the Activity History pane that contains GPS data. The activity log id will be in the URL, e.g. 213560689 in https://www.fitbit.com/activities/exercise/213560689 . The GPS activities appears in the Get Activities and Get Activities List endpoints contains GPS activities.
#' @param token An OAuth 2.0 token generated by oauth_token()
#' @param user_id	The encoded ID of the user. Use "-" (dash) for current logged-in user.
#' @param log_id	The activity's log ID.
#' @export
get_activity_TCX <- function()
{
  stop("Sorry, under construction")
  #GET https://api.fitbit.com/1/user/[user-id]/activities/[log-id].tcx
}

#' Activity Types
#'
#' Browse Activity Types
#' Get a tree of all valid Fitbit public activities from the activities catalog as well as private custom activities the user created in the format requested. If the activity has levels, also get a list of activity level details.
#' Typically, an applications retrieve the complete list of activities once at startup to cache and show in the UI later.
#' @export
activity_types <- function()
{
  #GET https://api.fitbit.com/1/activities.json
  url <- paste0(url_base, "activities.json")
  response <- get(url, token)
  content(response)
}


#' Get Activity Type
#'
#' Returns the details of a specific activity in the Fitbit activities database in the format requested.
#' If activity has levels, also returns a list of activity level details.
#'
#' @param token An OAuth 2.0 token generated by oauth_token()
#' @param activity_id	The activity ID.
#' @export
get_activity_type <- function(activity_id)
{
  #GET https://api.fitbit.com/1/activities/[activity-id].json
  url <- paste0(url_base, sprintf("activities/%s.json", activity_id))
  response <- get(url, token)
  convert_content_to_r_object(response)
}

#' Get Frequent Activities
#'
#' Retrieves a list of a user's frequent activities in the format requested using units in the unit system which corresponds to the Accept-Language header provided. A frequent activity record contains the distance and duration values recorded the last time the activity was logged. The record retrieved can be used to log the activity via the Log Activity endpoint with the same or adjusted values for distance and duration.
#' @export
get_frequent_activities <- function()
{
  #GET https://api.fitbit.com/1/user/-/activities/frequent.json
  url <- paste0(url_activity, "frequent.json")
  response <- get(url, token)
  convert_content_to_r_object(response)
}


#' Get Recent Activity Types
#'
#' Retrieves a list of a user's recent activities types logged with some details of the last activity log of that type using units in the unit system which corresponds to the Accept-Language header provided.
#' The record retrieved can be used to log the activity via the Log Activity endpoint with the same or adjusted values for distance and duration.
#'
#' @param token An OAuth 2.0 token generated by oauth_token()
#' @export
get_recent_activity_types <- function(token)
{
  url <- paste0(url_activity, "recent.json")
  response <- get(url, token)
  convert_content_to_r_object(response)
}

#' Get Favorite Activities
#'
#' Returns a list of a user's favorite activities.
#'
#' @param token An OAuth 2.0 token generated by oauth_token()
#' @export
get_favorite_activities <- function(token)
{
  url <- paste0(url_activity, "favorite.json")
  response <- get(url, token)
  convert_content_to_r_object(response)
}

#' Add Favorite Activity
#'
#' The Add Favorite Activity endpoint adds the activity with the given ID to user's list of favorite activities.
#' Note: A successful request returns a 201 response code with an empty body.
#'
#' @param token An OAuth 2.0 token generated by oauth_token()
#' @param activity_id	The ID of the activity to add to user's favorites.
#' @export
add_favorite_activity <- function(token, activity_id)
{
  #POST https://api.fitbit.com/1/user/-/activities/favorite/[activity-id].json
  url <- paste0(url_activity, sprintf("favorite/%s.json", activity_id))
  response <- post(url, token, list())
  convert_content_to_r_object(response)
}

#' Delete Favorite Activity
#' The Delete Favorite Activity removes the activity with the given ID from a user's list of favorite activities.
#' Note: A successful request returns a 204 status code with an empty response body.
#' @param token An OAuth 2.0 token generated by oauth_token()
#' @param activity-id	The ID of the activity to be removed.
#' @export
delete_favorite_activity <- function()
{
  url <- paste0(url_activity, sprintf("favorite/%s.json", activity_id))
  response <- delete(url, token)
  convert_content_to_r_object(response)
}

#' Get Activity Goals
#'
#' The Get Activity Goals retrieves a user's current daily or weekly activity goals using measurement units as defined in the unit system, which corresponds to the Accept-Language header provided.
#' Considerations
#' Only the current goals are returned.
#' Floors goal only returned for users who currently or have previously paired a Fitbit device with an altimeter.
#' Calories out goal represents either dynamic daily target from the Premium trainer plan or manual calorie burn goal.
#' The default daily goal values are:
#' 10 floors
#' 30 active minutes
#' Calories out is user specific, which accounts for BMR
#'
#' @param token An OAuth 2.0 token generated by oauth_token()
#' @param period	daily or weekly
#' @export
get_activity_goals <- function(token, period)
{
  url <- paste0(url_activity, sprintf("goals/%s.json", period))
  response <- get(url, token)
  convert_content_to_r_object(response)
}

#' Update Activity Goals
#'
#' The Update Activity Goals endpoint creates or updates a user's daily activity goals and returns a response using units in the unit system which corresponds to the Accept-Language header provided.
#' @param token An OAuth 2.0 token generated by oauth_token()
#' @param period	daily or weekly
#' @param caloriesOut	optional	Goal value; integer.
#' @param activeMinutes	optional	Goal value; integer.
#' @param floors	optional	Goal value; integer.
#' @param distance	optional	Goal value; in the format X.XX or integer.
#' @param steps	optional	Goal value; integer.
#' @export
update_activity_goals <- function(token)
{
  #POST https://api.fitbit.com/1/user/[user-id]/activities/goals/[period].json
  url <- paste0(url_activity, sprintf("goals/%s.json", period))
  response <- post(url, token)
  convert_content_to_r_object(response)
}

#' Get Lifetime Stats
#'
#' Retrieves the user's activity statistics in the format requested using units in the unit system which corresponds to the Accept-Language header provided. Activity statistics includes Lifetime and Best achievement values from the My Achievements tile on the website dashboard. Response contains both statistics from the tracker device and total numbers including tracker data and manual activity log entries as seen on the Fitbit website dashboard.
#'
#' Privacy Setting
#' The My Achievements (Friends or Anyone) privacy permission grants access to user's resource.
#'
#' @param token An OAuth 2.0 token generated by oauth_token()
#' @export
get_lifetime_stats <- function(token)
{
  #GET https://api.fitbit.com/1/user/[user-id]/activities.json
  url <- paste0(url_api, "activities.json")
  response <- get(url, token)
  convert_content_to_r_object(response)
}
