#' @include fitbitr.R
#Constants
url_activity <- paste0(url_api, "activities/")

#' Get Daily Activity Summary
#'
#' Retrieves a summary and list of a user's activities and activity log entries for a given day in the format requested using units in the unit system which corresponds to the Accept-Language header provided.
#'
#' Daily summary data and daily goals for elevation (elevation, floors) only included for users with a device with an altimeter.
#' The steps field in activity log entires included only for activities that have steps (e.g. "Walking", "Running"); distance only included when it is relevant.
#' A false value for field means that activity log entry was created without explicit start time via some of our data import workflows. The field for such entry is commonly set to 00:00.
#' Calorie burn goal (caloriesOut) represents either dynamic daily target from the premium trainer plan or manual calorie burn goal. Goals are included to the response only for today and 21 days in the past.
#' @param token An OAuth 2.0 token generated by oauth_token()
#' @param date The date in the format yyyy-MM-dd
#' @export
get_daily_activity_summary <- function(token, date)
{
  url <- paste0(url_activity, sprintf("date/%s.json", format_date(date)))
  response <- get(url, token)
  convert_content_to_r_object(response)
}
