#' @include fitbitr.R
#Constants
url_body <- paste0(url_api, "body/")

#' Get Body Fat Logs
#' The Get Body Fat Logs API retrieves a list of all user's body fat log entries for a given day in the format requested. Body fat log entries are available only to authorized user. If you need to fetch only the most recent entry, you can use the Get Body Measurements endpoint.
#'
#' @param token An OAuth 2.0 token generated by oauth_token()
#' @param date	The date in the format yyyy-MM-dd.
#' @param period	The date range period. One 1d, 7d, 1w, 1m.
#' @param base_date	The end date when period is provided; range start date when a date range is provided. In the format yyyy-MM-dd or today.
#' @param end_date	Range end date when date range is provided. Note: The range should not be longer than 31 days
#' @export
get_body_fat_logs <- function(token, date="", period="", base_date="", end_date="")
{
  url <- if(date != ""){
    if(period != ""){
      paste0(url_body, sprintf("log/fat/date/%s/%s.json", format_date(date), period))
    } else{
      paste0(url_body, sprintf("log/fat/date/%s.json",    format_date(date)))
    }
  } else if(base_date != "" & end_date != ""){
    paste0(url_body, sprintf("date/%s/%s.json", format_date(base_date), format_date(end_date)))
  }

  response <- get(url, token)
  convert_content_to_r_object(response)
}

#' Log Body Fat
#' The Log Body Fat API creates a log entry for body fat and returns a response in the format requested.
#' Note: The returned Body Fat Log IDs are unique to the user, but not globally unique.
#'
#' @param token An OAuth 2.0 token generated by oauth_token()
#' @param fat Body fat; in the format X.XX
#' @param date Log entry date; in the format yyyy-MM-dd.
#' @param time optional	Time of the measurement; hours and minutes in the format HH:mm:ss, set to the last second of the day if not provided.
#' @export
log_body_fat <- function(token, fat, date, time="")
{
  url <- paste0(url_body, "log/fat.json")
  body <- c(list(fat=fat, date=date), if(time != ""){list(time=time)}else{NULL})
  response <- post(url, token, body=body)
  convert_content_to_r_object(response)
}

#' Delete Body Fat Log
#' The Delete Body Fat Log API deletes a user's body fat log entry with the given ID.
#' Note: A successful request returns a 204 status code with an empty response body.
#'
#' @param token An OAuth 2.0 token generated by oauth_token()
#' @param body_fat_log_id	The ID of the body fat log entry.
#' @export
delete_body_fat_log <- function(token, body_fat_log_id)
{
  url <- paste0(url_body, sprintf("log/fat/%s.json", body_fat_log_id))
  delete(url, token)
}

#' Get Body Time Series
#' The Get Body Time Series API returns time series data in the specified range for a given resource
#' Note: If you provide earlier dates in the request, the response retrieves only data since the user's join date or the first log entry date for the requested collection.
#'
#' @param token An OAuth 2.0 token generated by oauth_token()
#' @param resource_path	The resource path. Options are "bmi", "fat", or "weight".
#' @param date	The end date of the period specified in the format yyyy-MM-dd or today.
#' @param period	The range for which data will be returned. Options are 1d, 7d, 30d, 1w, 1m, 3m, 6m, 1y, or max.
#' @param base_date	The range start date, in the format yyyy-MM-dd or today.
#' @param end_date	The end date of the range.
#' @export
get_body_time_series <- function(token, resource_path, date="", period="", base_date="", end_date="")
{
  url <- if(date != "" && period != ""){
    paste0(url_body, sprintf("%s/date/%s/%s.json", resource_path, format_date(date), period))
  } else if(base_date != "" & end_date != ""){
    paste0(url_body, sprintf("%s/date/%s/%s.json", resource_path, format_date(base_date), format_date(end_date)))
  }
  response <- get(url, token)
  data <- convert_content_to_r_object(response)
  data[[1]]
}

#' Get Body Goals
#' The Get Body Goals API retrieves a user's current body fat percentage or weight goal using units in the unit systems that corresponds to the Accept-Language header provided in the format requested.
#'
#' @param token An OAuth 2.0 token generated by oauth_token()
#' @param goal_type	weight or fat
#' @export
get_body_goals <- function(token, goal_type)
{
  url <- paste0(url_body, sprintf("log/%s.json", goal_type))
  response <- get(url, token)
  convert_content_to_r_object(response)
}

#' Update Body Fat Goal
#' The Update Body Fat Goal API creates or updates user's fat percentage goal.
#'
#' @param token An OAuth 2.0 token generated by oauth_token()
#' @param fat	Target body fat percentage; in the format X.XX.
#' @export
update_body_fat_goal <- function(token, fat)
{
  url <- paste0(url_body, "log/fat/goal.json")
  response <- post(url, token, body=list(fat=fat))
  convert_content_to_r_object(response)
}

#' Update Weight Goal
#' The Update Weight Goal API creates or updates user's fat or weight goal using units in the unit systems that corresponds to the Accept-Language header provided in the format requested.
#'
#' @param token An OAuth 2.0 token generated by oauth_token()
#' @param startDate Weight goal start date; in the format yyyy-MM-dd.
#' @param startWeight	Weight goal start weight; in the format X.XX, in the unit systems that corresponds to the Accept-Language header provided.
#' @param weight required/optional	Weight goal target weight; in the format X.XX, in the unit systems that corresponds to the Accept-Language header provided; required if user doesn't have an existing weight goal.
#' @export
update_body_weight_goal <- function(token, startDate, startWeight, weight="")
{
  url <- paste0(url_body, "log/weight/goal.json")
  response <- post(url, token, body=list(startDate=startDate, startWeight=startWeight))
  convert_content_to_r_object(response)
}

#' Get Weight Logs
#' The Get Weight Logs API retrieves a list of all user's body weight log entries for a given day using units in the unit systems which corresponds to the Accept-Language header provided. Body weight log entries are available only to authorized user. Body weight log entries in response are sorted exactly the same as they are presented on the Fitbit website.
#'
#' @param token An OAuth 2.0 token generated by oauth_token()
#' @param date	The date in the format yyyy-MM-dd.
#' @param period	The date range period. One of 1d, 7d, 30d, 1w, 1m.
#' @param base_date	The end date when period is provided, in the format yyyy-MM-dd; range start date when a date range is provided.
#' @param end_date	Range end date when date range is provided. Note: The period must not be longer than 31 days.
#' @export
get_weight_logs <- function(token, date="", period="", base_date="", end_date="")
{
  url <- if(date != ""){
    if(period != ""){
      paste0(url_body, sprintf("log/weight/date/%s/%s.json", format_date(date), period))
    } else{
      paste0(url_body, sprintf("log/weight/date/%s.json",    format_date(date)))
    }
  } else if(base_date != "" & end_date != ""){
    paste0(url_body, sprintf("date/%s/%s.json", format_date(base_date), format_date(end_date)))
  }

  response <- get(url, token)
  data <- convert_content_to_r_object(response)
  data[[1]]
}

#' Log Weight
#' The Log Weight API creates log entry for a body weight using units in the unit systems that corresponds to the Accept-Language header provided and get a response in the format requested.
#' Note: The returned Weight Log IDs are unique to the user, but not globally unique.
#'
#' @param token An OAuth 2.0 token generated by oauth_token()
#' @param weight	required	Weight - in the format X.XX.
#' @param date	required	Log entry date - in the format yyyy-MM-dd.
#' @param time	optional	Time of the measurement - hours and minutes in the format HH:mm:ss, which is set to the last second of the day if time is not provided.
#' @export
log_weight <- function(token, weight, date, time="")
{
  url <- paste0(url_body, "log/weight.json")
  body <- c(list(weight=weight, date=date), if(time != ""){list(time=time)}else{NULL})
  response <- post(url, token, body=body)
  convert_content_to_r_object(response)
}

#' Delete Weight Log
#' The Delete Weight Log API deletes a user's body weight log entry with the given ID.
#' Note: A successful request returns a 204 status code with an empty response body.
#'
#' @param token An OAuth 2.0 token generated by oauth_token()
#' @param body_weight_log_id	The ID of the body weight log entry.
#' @export
delete_weight_log <- function(token, body_weight_log_id)
{
  url <- paste0(url_body, sprintf("log/weight/%s.json", body_weight_log_id))
  delete(url, token)
}
