#' Generate an oauth token for fitbit
#'
#' OAuth token will be generated by "Client" as OAuth 2.0 Application Type.
#' If you want to use "Personal" type, plesase set key and secret variable. In this case, you have to register your own application on https://dev.fitbit.com/jp.
#'
#' @param key client key generated by your own
#' @param secret secret key generated by your own
#' @export
oauth_token <- function(key=NULL, secret=NULL){
  if((is.null(key) && !is.null(secret)) || (!is.null(key) && is.null(secret))){
    stop("Both of key and secret are given.")
  }

  #Client type setting.
  if(is.null(key) && is.null(secret)){
    key    <- "227QG2"
    secret <- "fd2090a1c5cc11194210bd4bd113b7d0"
  }

  request <- "https://api.fitbit.com/oauth2/token"
  authorize <- "https://www.fitbit.com/oauth2/authorize"
  access <- "https://api.fitbit.com/oauth2/token"
  endpoint <- httr::oauth_endpoint(request, authorize, access)
  myapp <- httr::oauth_app("r-package", key, secret)
  scope <- c("sleep", "activity", "heartrate", "location", "nutrition", "profile", "settings", "social", "weight")
  httr::oauth2.0_token(endpoint, myapp, scope=scope, use_basic_auth=TRUE, cache=FALSE)
}
