#' Generate an oauth token for fitbit
#'
#' OAuth token will be generated by "Client" as OAuth 2.0 Application Type.
#' If you want to use "Personal" type, plesase set key and secret variable. In this case, you have to register your own application on https://dev.fitbit.com/jp.
#'
#' @param key client key generated by your own
#' @param secret secret key generated by your own
#' @export
oauth_token <- function(key=NULL, secret=NULL){
  if((is.null(key) && !is.null(secret)) || (!is.null(key) && is.null(secret))){
    stop("Both of key and secret are given.")
  }

  #Load key automatically from global or environmnt variable
  if(is.null(key) && is.null(secret)){
    if(exists("FITBIT_KEY") && exists("FITBIT_SECRET")){
      key    <- FITBIT_KEY
      secret <- FITBIT_SECRET
    }else{
      #Client type setting.
      key    <- "227QG2"
      secret <- "fd2090a1c5cc11194210bd4bd113b7d0"
    }
  }
  # We have to the last backslash(/) from the callback URL because fitbit API does not look like allowing it.
  # How to change the callback function is based on: https://github.com/hadley/httr/issues/43#issuecomment-20104231
  assignInNamespace("oauth_callback", pos = "package:httr", function() {
    "http://localhost:1410"
  })
  request <- "https://api.fitbit.com/oauth2/token"
  authorize <- "https://www.fitbit.com/oauth2/authorize"
  access <- "https://api.fitbit.com/oauth2/token"
  endpoint <- httr::oauth_endpoint(request, authorize, access)
  myapp <- httr::oauth_app("r-package", key, secret)
  scope <- c("sleep", "activity", "heartrate", "location", "nutrition", "profile", "settings", "social", "weight")
  httr::oauth2.0_token(endpoint, myapp, scope=scope, use_basic_auth=TRUE, cache=FALSE)
}
